# Generated by Django 4.0.2 on 2022-02-07 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.PositiveIntegerField(verbose_name='Quantity')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='webapp.good', verbose_name='Good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='webapp.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Good in order',
                'verbose_name_plural': 'Goods in order',
                'db_table': 'OrderGood',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(related_name='orders', through='webapp.OrderGood', to='webapp.Good', verbose_name='Goods'),
        ),
    ]
