# Generated by Django 4.0.2 on 2022-02-07 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_order_ordergood_order_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='remainder',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
